package com.shadowtradingplatform.trade.domain.po;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.LocalDateTime;
import lombok.Data;
import lombok.EqualsAndHashCode;
import org.springframework.format.annotation.DateTimeFormat;

/**
 * cart 实体类
 * 
 * @author Generated by huanglingjiekou
 * @date 2026-08-12 16:48:14
 */
@Data
@EqualsAndHashCode(callSuper = false)
@TableName("cart")
@Schema(description = "cart表实体类")
public class Cart {

    @Schema(description = "购物车项ID", required = true)
    @TableId(type = IdType.AUTO)
    private Long id;

    @Schema(description = "用户ID", required = true)
    @TableField("user_id")
    private Long userId;

    @Schema(description = "商品ID", required = true)
    @TableField("product_id")
    private Long productId;

    @Schema(description = "数量", required = true)
    @TableField("quantity")
    private Integer quantity;

    @Schema(description = "是否选中：0=否 1=是", required = true)
    @TableField("selected")
    private Integer selected;

    @Schema(description = "创建时间", required = true)
    @TableField("create_time")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime createTime;

    @Schema(description = "更新时间", required = true)
    @TableField("update_time")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime updateTime;

}