package com.shadowtradingplatform.trade.domain.po;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.v3.oas.annotations.media.Schema;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import lombok.Data;
import lombok.EqualsAndHashCode;
import org.springframework.format.annotation.DateTimeFormat;

/**
 * coupon 实体类
 * 
 * @author Generated by huanglingjiekou
 * @date 2026-08-12 16:48:14
 */
@Data
@EqualsAndHashCode(callSuper = false)
@TableName("coupon")
@Schema(description = "coupon表实体类")
public class Coupon {

    @Schema(description = "优惠券ID", required = true)
    @TableId(type = IdType.AUTO)
    private Long id;

    @Schema(description = "券名称", required = true)
    @TableField("title")
    private String title;

    @Schema(description = "满减金额", required = true)
    @TableField("amount")
    private BigDecimal amount;

    @Schema(description = "使用门槛（满 min_spend 可用）", required = true)
    @TableField("min_spend")
    private BigDecimal minSpend;

    @Schema(description = "适用范围描述", required = false)
    @TableField("scope")
    private String scope;

    @Schema(description = "有效期开始", required = true)
    @TableField("valid_start")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime validStart;

    @Schema(description = "有效期结束", required = true)
    @TableField("valid_end")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime validEnd;

    @Schema(description = "发行总量", required = true)
    @TableField("total")
    private Integer total;

    @Schema(description = "已领取数（冗余计数）", required = true)
    @TableField("claimed")
    private Integer claimed;

    @Schema(description = "状态：0=可领取 1=已抢光", required = true)
    @TableField("status")
    private Integer status;

    @Schema(description = "创建时间", required = true)
    @TableField("create_time")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime createTime;

    @Schema(description = "更新时间", required = true)
    @TableField("update_time")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime updateTime;

}