package com.shadowtradingplatform.trade.domain.po;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * product_image 实体类
 * 
 * @author Generated by huanglingjiekou
 * @date 2026-08-12 16:48:14
 */
@Data
@EqualsAndHashCode(callSuper = false)
@TableName("product_image")
@Schema(description = "product_image表实体类")
public class ProductImage {

    @Schema(description = "主键", required = true)
    @TableId(type = IdType.AUTO)
    private Long id;

    @Schema(description = "商品ID", required = true)
    @TableField("product_id")
    private Long productId;

    @Schema(description = "图片URL", required = true)
    @TableField("image_url")
    private String imageUrl;

    @Schema(description = "排序（升序）", required = true)
    @TableField("sort_order")
    private Integer sortOrder;

}