package com.shadowtradingplatform.trade.domain.po;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.v3.oas.annotations.media.Schema;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import lombok.Data;
import lombok.EqualsAndHashCode;
import org.springframework.format.annotation.DateTimeFormat;

/**
 * product 实体类
 * 
 * @author Generated by huanglingjiekou
 * @date 2026-08-12 16:48:14
 */
@Data
@EqualsAndHashCode(callSuper = false)
@TableName("product")
@Schema(description = "product表实体类")
public class Product {

    @Schema(description = "商品ID", required = true)
    @TableId(type = IdType.AUTO)
    private Long id;

    @Schema(description = "商品名称", required = true)
    @TableField("name")
    private String name;

    @Schema(description = "副标题", required = false)
    @TableField("subtitle")
    private String subtitle;

    @Schema(description = "售价", required = true)
    @TableField("price")
    private BigDecimal price;

    @Schema(description = "原价", required = false)
    @TableField("original_price")
    private BigDecimal originalPrice;

    @Schema(description = "主图URL", required = false)
    @TableField("image")
    private String image;

    @Schema(description = "分类：digital/accessory/audio", required = true)
    @TableField("category")
    private String category;

    @Schema(description = "销量", required = true)
    @TableField("sales")
    private Integer sales;

    @Schema(description = "库存", required = true)
    @TableField("stock")
    private Integer stock;

    @Schema(description = "简述", required = false)
    @TableField("description")
    private String description;

    @Schema(description = "富文本详情", required = false)
    @TableField("detail")
    private String detail;

    @Schema(description = "上架状态：0=下架 1=上架", required = true)
    @TableField("status")
    private Integer status;

    @Schema(description = "创建时间", required = true)
    @TableField("create_time")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime createTime;

    @Schema(description = "更新时间", required = true)
    @TableField("update_time")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime updateTime;

}