package com.shadowtradingplatform.trade.domain.po;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;
import lombok.EqualsAndHashCode;

/**
 * tag 实体类
 * 
 * @author Generated by huanglingjiekou
 * @date 2026-08-12 16:48:14
 */
@Data
@EqualsAndHashCode(callSuper = false)
@TableName("tag")
@Schema(description = "tag表实体类")
public class Tag {

    @Schema(description = "标签ID", required = true)
    @TableId(type = IdType.AUTO)
    private Long id;

    @Schema(description = "标签名", required = true)
    @TableField("name")
    private String name;

}