package com.shadowtradingplatform.trade.domain.po;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.LocalDateTime;
import lombok.Data;
import lombok.EqualsAndHashCode;
import org.springframework.format.annotation.DateTimeFormat;

/**
 * user 实体类
 * 
 * @author Generated by huanglingjiekou
 * @date 2026-08-12 16:48:14
 */
@Data
@EqualsAndHashCode(callSuper = false)
@TableName("user")
@Schema(description = "user表实体类")
public class User {

    @Schema(description = "用户ID", required = true)
    @TableId(type = IdType.AUTO)
    private Long id;

    @Schema(description = "登录用户名", required = true)
    @TableField("username")
    private String username;

    @Schema(description = "密码（加盐哈希，如 BCrypt）", required = true)
    @TableField("password")
    private String password;

    @Schema(description = "昵称", required = false)
    @TableField("nickname")
    private String nickname;

    @Schema(description = "头像URL", required = false)
    @TableField("avatar")
    private String avatar;

    @Schema(description = "手机号", required = false)
    @TableField("phone")
    private String phone;

    @Schema(description = "创建时间", required = true)
    @TableField("create_time")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime createTime;

    @Schema(description = "更新时间", required = true)
    @TableField("update_time")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime updateTime;

}