package com.shadowtradingplatform.trade.domain.po;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.v3.oas.annotations.media.Schema;
import java.time.LocalDateTime;
import lombok.Data;
import lombok.EqualsAndHashCode;
import org.springframework.format.annotation.DateTimeFormat;

/**
 * user_coupon 实体类
 * 
 * @author Generated by huanglingjiekou
 * @date 2026-08-12 16:48:14
 */
@Data
@EqualsAndHashCode(callSuper = false)
@TableName("user_coupon")
@Schema(description = "user_coupon表实体类")
public class UserCoupon {

    @Schema(description = "主键", required = true)
    @TableId(type = IdType.AUTO)
    private Long id;

    @Schema(description = "用户ID", required = true)
    @TableField("user_id")
    private Long userId;

    @Schema(description = "优惠券ID", required = true)
    @TableField("coupon_id")
    private Long couponId;

    @Schema(description = "状态：0=未使用 1=已使用 2=已过期", required = true)
    @TableField("status")
    private Integer status;

    @Schema(description = "领取时间", required = true)
    @TableField("claim_time")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime claimTime;

    @Schema(description = "使用时间", required = false)
    @TableField("use_time")
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+8")
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime useTime;

}